# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 08:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainpict',
            field=models.FileField(default='img/post01.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
