# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161010_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainpict',
            field=models.FileField(default='uploads/Pxjq6.jpg', upload_to='uploads/'),
        ),
    ]
