# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161010_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pdate']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='cdate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='pdate',
        ),
    ]
