# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161010_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kurs',
            field=models.CharField(default='1617PHEFGK2', max_length=15),
        ),
    ]
