# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
