# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161016_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='atachement1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='atachement2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='atachement3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(max_length=300),
        ),
    ]
